# This data file contains information used by the kanji generator system.
# For instance, orientation and size information for radicals

# Example entry:
#
# [[radicals]]
# name = "beast"          -- A convenient label for this radical.
#                            Optional, but must be unique if specified.
# char = "犭"             -- The Unicode character corresponding to this radical, if any.
# file = "072ad.svg"      -- The path to the SVG file with this radical. Optional if "char" is given.
# pos = 0                 -- Which position this radical takes.
#                            For left or top radicals, it should be 0,
#                            For right or bottom radicals, it should be 1.
#                            This basically describes, in the lists to follow,
#                            which item is this radical, leaving the other for the
#                            combining character.
# x = [0, 25]             -- The x positions for the elements. The "pos" item is the radical.
# y = [0, 0]              -- The y positions for the elements.
# width = [34, 85]        -- The widths for the elements.
# height = [109, 109]     -- The heights for the elements.
# stroke = [1, 1.2]       -- The factor to multiply each of the radicals' stroke width by.
#                            Optional, if excluded value is [1, 1] (leave unchanged).
# viewbox = "0 0 42 109"  -- The viewbox to use for the radical itself.
#                            The combining character is assumed to have the default viewbox.

###
# LEFT
###

[[radicals]]
name = "beast"
char = "犭"
pos = 0
x = [0, 28]
y = [0, 0]
width = [36, 85]
height = [109, 109]
viewbox = "0 0 42 109"

###
# RIGHT
###

# TODO

###
# BOTTOM
###

# TODO

###
# INSIDE
###

# TODO

###
# CORNER
###

[[radicals]]
name = "street"
char = "⻌"
pos = 1
x = [26, 0]
y = [5, 0]
width = [78, 109]
height = [90, 109]
stroke = [1.28, 1]
viewbox = "0 0 109 109"
