# This data file contains information used by the kanji generator system.
# For instance, orientation and size information for radicals, as well as
# radicals to extract from full characters (since they are unavaiable individually)

###
# Exclusions section
###

# This is a list of characters to not copy.
#
# Even though they are in KanjiVG, we aren't going to use them
# usually because they are radicals or not used in Japanese.

exclude = [
    "个",
    "丶",
    "亅",
    "⻃",
    "⺨",
]

###
# Radicals section
#
# also includes extractions next to the radical it pulls
###

# [[radical]]
# name = "beast"          -- A convenient label for this radical.
#                            Optional, but must be unique if specified.
# char = "犭"             -- The Unicode character corresponding to this radical, if any.
# file = "072ad.svg"      -- The path to the SVG file with this radical. Optional if "char" is given.
# pos = 0                 -- Which position this radical takes.
#                            For left or top radicals, it should be 0,
#                            For right or bottom radicals, it should be 1.
#                            This basically describes, in the lists to follow,
#                            which item is this radical, leaving the other for the
#                            combining character.
# x = [0, 25]             -- The x positions for the elements. The "pos" item is the radical.
# y = [0, 0]              -- The y positions for the elements.
# width = [34, 85]        -- The widths for the elements.
# height = [109, 109]     -- The heights for the elements.
# stroke = [1, 1.2]       -- The factor to multiply each of the radicals' stroke width by.
#                            Optional, if excluded value is [1, 1] (leave unchanged).
# viewbox = "0 0 42 109"  -- The viewbox to use for the radical itself.
#                            The combining character is assumed to have the default viewbox.

# [[extraction]]
# name = "grain-left"     -- A convenient label for this version of this radical.
# input = "079d5.svg"     -- The file that this radical is being extracted from.
# output = "079be.svg"    -- The output file to write to. Optional.
#                            By default this is the hex version of "element",
#                            but this must be overridden if element is multiple
#                            characters or the target is incorrect or already used
#                            by another radical file.
# element = "禾"          -- The value for "kvg:element" to look for.
#
#
# Remember any extractions need "copy = false" for their corresponding radical data!

###
# LEFT
###

[[radical]]
name = "stick"
char = "丨"
pos = 0
x = [0, 17]
y = [10, 0]
width = [25, 92]
height = [90, 109]
viewbox = "30 0 30 109"

[[extraction]]
name = "craft-left"
input = "05de7.svg"
element = "工"

[[radical]]
name = "craft"
char = "工"
pos = 0
x = [0, 32]
width = [40, 77]
viewbox = "0 0 50 109"
copy = false

[[radical]]
name = "grain"
char = "禾"
pos = 0
x = [0, 30]
width = [40, 79]
viewbox = "0 0 47 109"
copy = false

[[extraction]]
name = "grain-left"
input = "079d5.svg"
element = "禾"

[[radical]]
name = "beast"
char = "犭"
pos = 0
x = [0, 30]
width = [36, 82]
viewbox = "0 0 42 109"

[[radical]]
name = "horse"
char = "馬"
pos = 0
x = [0, 33]
width = [40, 76]
viewbox = "0 0 50 109"
copy = false

[[extraction]]
name = "horse-left"
input = "099bc.svg"
element = "馬"

###
# RIGHT
###

# TODO

[[extraction]]
name = "culture-right"
input = "099bc.svg"
element = "文"

###
# TOP
###

[[radical]]
name = "west"
char = "覀"
pos = 0
y = [0, 28]
height = [34, 72]
viewbox = "0 0 109 51"

[[extraction]]
name = "west"
input = "08981.svg"
element = "覀"

[[radical]]
name = "outhouse"
file = "2ba60.svg"
pos = 0
y = [0, 36]
height = [46, 73]
viewbox = "0 0 109 73"

[[extraction]]
name = "outhouse"
input = "05802.svg"
output = "2ba60.svg"
element = "尚"

###
# BOTTOM
###

# TODO

###
# INSIDE
###

# TODO

###
# CORNER
###

[[radical]]
name = "street"
char = "⻌"
pos = 1
x = [26, 0]
y = [10, 0]
width = [78, 109]
height = [80, 109]
stroke = [1.28, 1]
viewbox = "0 0 109 109"
